FROM ubuntu:latest

# Update system and install Python, pip, and git
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    git

# Install Python package
RUN pip3 install pyyaml

# Copy files into the container
COPY feed.py /app/feed.py
COPY entrypoint.sh /entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /entrypoint.sh

# Set working directory
WORKDIR /app

# Set entrypoint
ENTRYPOINT ["/entrypoint.sh"]
